-- ═══════════════════════════════════════════════════════════════════════════
-- 15 — Tables for the sixteen modules added in migration 14
--
-- Conventions, all inherited from migrations 02 and 03 rather than reinvented:
--
--   · Every top-level entity carries `org_id` and gets `app.apply_standard_rls`.
--     Line items and other rows that only exist inside a parent get
--     `app.apply_child_rls`, which reads isolation off the parent instead of
--     duplicating an org_id that could disagree with it.
--   · Money is `bigint` minor units, never numeric and never text.
--   · Soft delete via `deleted_at` on anything a user can remove by mistake;
--     line items are hard-deleted with their parent, since a "deleted" invoice
--     line that still counts toward a total is a bug, not a record.
--   · Human-readable codes come from `app.set_code`, so they are unique per
--     organization and never collide across tenants.
--   · Enumerated columns match the vocabularies in src/lib/domain.ts exactly,
--     accents included: the constraint compares literal strings.
--
-- Not every module here starts from nothing. Migration 02 already created
-- `job_openings`, `candidates`, `courses`, `course_enrollments`,
-- `certifications` and `evaluations` — thin scaffolding, gated on
-- `empleados:read/write`, with no query, mutation or seed reading them. Those
-- are widened and re-pointed at their own module permission below rather than
-- duplicated: a second `candidates` table would have made "how many people
-- applied" a question with two answers.
-- ═══════════════════════════════════════════════════════════════════════════

/**
 * Moves a table from one permission pair to another.
 *
 * `app.apply_standard_rls` creates policies with fixed, derived names, so the
 * old four can be dropped by name and the new four generated by the same
 * function the rest of the schema uses. Re-pointing by hand would mean writing
 * the four policy bodies again, which is how one of them ends up subtly
 * different from every other table in the database.
 */
create or replace function app.repoint_standard_rls(
  p_table      text,
  p_read_perm  text,
  p_write_perm text
)
returns void
language plpgsql
as $$
begin
  execute format('drop policy if exists %I on public.%I', p_table || '_select', p_table);
  execute format('drop policy if exists %I on public.%I', p_table || '_insert', p_table);
  execute format('drop policy if exists %I on public.%I', p_table || '_update', p_table);
  execute format('drop policy if exists %I on public.%I', p_table || '_delete', p_table);
  perform app.apply_standard_rls(p_table, p_read_perm, p_write_perm);
end;
$$;

create or replace function app.repoint_child_rls(
  p_table        text,
  p_parent_table text,
  p_fk_column    text,
  p_read_perm    text,
  p_write_perm   text
)
returns void
language plpgsql
as $$
begin
  execute format('drop policy if exists %I on public.%I', p_table || '_select', p_table);
  execute format('drop policy if exists %I on public.%I', p_table || '_insert', p_table);
  execute format('drop policy if exists %I on public.%I', p_table || '_update', p_table);
  execute format('drop policy if exists %I on public.%I', p_table || '_delete', p_table);
  perform app.apply_child_rls(p_table, p_parent_table, p_fk_column, p_read_perm, p_write_perm);
end;
$$;

revoke all on function app.repoint_standard_rls(text, text, text) from public, anon, authenticated;
revoke all on function app.repoint_child_rls(text, text, text, text, text) from public, anon, authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- Clientes (CRM)
--
-- The gap this closes: `quotes.client` and `invoices` were free text. Two
-- quotes for the same customer spelled differently were two customers, and
-- nothing could answer "what is this account worth".
-- ═══════════════════════════════════════════════════════════════════════════

create table public.clients (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references public.organizations (id) on delete cascade,
  code          text,
  name          text not null check (length(btrim(name)) between 1 and 160),
  legal_name    text not null default '',
  tax_id        text not null default '',
  kind          text not null default 'Empresa'
                  check (kind in ('Empresa', 'Persona natural', 'Entidad pública', 'Otro')),
  status        text not null default 'Prospecto'
                  check (status in ('Prospecto', 'Activo', 'Inactivo', 'Perdido')),
  industry      text not null default '',
  email         text check (email is null or email = lower(email)),
  phone         text not null default '',
  address       text not null default '',
  city          text not null default '',
  owner_id      uuid references public.employees (id) on delete set null,
  credit_limit_cents bigint not null default 0 check (credit_limit_cents >= 0),
  payment_terms_days smallint not null default 0 check (payment_terms_days between 0 and 365),
  notes         text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,
  unique (org_id, code)
);

create index clients_org_idx on public.clients (org_id, status) where deleted_at is null;

create trigger clients_code  before insert on public.clients
  for each row execute function app.set_code('client', 'CLI', '4');
create trigger clients_touch before update on public.clients
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('clients', 'clientes:read', 'clientes:write');

create table public.client_contacts (
  id          uuid primary key default gen_random_uuid(),
  client_id   uuid not null references public.clients (id) on delete cascade,
  full_name   text not null,
  position    text not null default '',
  email       text check (email is null or email = lower(email)),
  phone       text not null default '',
  -- Exactly one contact per client is the one you call first. Enforced by the
  -- partial unique index below rather than by convention.
  is_primary  boolean not null default false,
  created_at  timestamptz not null default now()
);

create index client_contacts_client_idx on public.client_contacts (client_id);
create unique index client_contacts_primary_key
  on public.client_contacts (client_id) where is_primary;

select app.apply_child_rls('client_contacts', 'clients', 'client_id',
                           'clientes:read', 'clientes:write');

create table public.client_interactions (
  id          uuid primary key default gen_random_uuid(),
  client_id   uuid not null references public.clients (id) on delete cascade,
  kind        text not null default 'Nota'
                check (kind in ('Llamada', 'Correo', 'Reunión', 'Visita', 'Nota')),
  subject     text not null default '',
  detail      text not null default '',
  employee_id uuid references public.employees (id) on delete set null,
  happened_at timestamptz not null default now(),
  follow_up_on date,
  created_at  timestamptz not null default now()
);

create index client_interactions_client_idx
  on public.client_interactions (client_id, happened_at desc);

select app.apply_child_rls('client_interactions', 'clients', 'client_id',
                           'clientes:read', 'clientes:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Facturación
--
-- `total_cents` is stored, not computed on read. A historical invoice must
-- keep the total it was issued with even after a product's price changes, and
-- a view that recomputes it from today's catalogue quietly rewrites the past.
-- ═══════════════════════════════════════════════════════════════════════════

create table public.invoices (
  id             uuid primary key default gen_random_uuid(),
  org_id         uuid not null references public.organizations (id) on delete cascade,
  code           text,
  client_id      uuid references public.clients (id) on delete set null,
  -- Kept alongside the FK: an invoice must still print the name it was issued
  -- to even if the client row is later removed.
  client_name    text not null default '',
  quote_id       uuid references public.quotes (id) on delete set null,
  project_id     uuid references public.projects (id) on delete set null,
  status         text not null default 'Borrador'
                   check (status in ('Borrador', 'Emitida', 'Pagada', 'Vencida', 'Anulada')),
  issued_on      date not null default current_date,
  due_on         date,
  subtotal_cents bigint not null default 0 check (subtotal_cents >= 0),
  tax_cents      bigint not null default 0 check (tax_cents >= 0),
  total_cents    bigint not null default 0 check (total_cents >= 0),
  paid_cents     bigint not null default 0 check (paid_cents >= 0),
  currency       text not null default 'COP' check (currency ~ '^[A-Z]{3}$'),
  notes          text not null default '',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz,
  unique (org_id, code),
  constraint invoices_dates_ordered check (due_on is null or due_on >= issued_on),
  -- Overpayment is a data-entry error, not a state the reports should carry.
  constraint invoices_paid_within_total check (paid_cents <= total_cents)
);

create index invoices_org_idx on public.invoices (org_id, status) where deleted_at is null;
create index invoices_client_idx on public.invoices (client_id) where deleted_at is null;
create index invoices_due_idx on public.invoices (org_id, due_on)
  where deleted_at is null and status in ('Emitida', 'Vencida');

create trigger invoices_code  before insert on public.invoices
  for each row execute function app.set_code('invoice', 'FAC', '5');
create trigger invoices_touch before update on public.invoices
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('invoices', 'facturacion:read', 'facturacion:write');

create table public.invoice_items (
  id            uuid primary key default gen_random_uuid(),
  invoice_id    uuid not null references public.invoices (id) on delete cascade,
  product_id    uuid references public.products (id) on delete set null,
  description   text not null,
  quantity      numeric(12,2) not null default 1 check (quantity > 0),
  unit_price_cents bigint not null default 0 check (unit_price_cents >= 0),
  tax_rate      numeric(5,2) not null default 0 check (tax_rate between 0 and 100),
  position      smallint not null default 0
);

create index invoice_items_invoice_idx on public.invoice_items (invoice_id, position);

select app.apply_child_rls('invoice_items', 'invoices', 'invoice_id',
                           'facturacion:read', 'facturacion:write');

create table public.invoice_payments (
  id           uuid primary key default gen_random_uuid(),
  invoice_id   uuid not null references public.invoices (id) on delete cascade,
  amount_cents bigint not null check (amount_cents > 0),
  method       text not null default 'Transferencia'
                 check (method in ('Transferencia', 'Efectivo', 'Tarjeta', 'Cheque', 'Otro')),
  reference    text not null default '',
  paid_on      date not null default current_date,
  created_at   timestamptz not null default now()
);

create index invoice_payments_invoice_idx on public.invoice_payments (invoice_id, paid_on);

select app.apply_child_rls('invoice_payments', 'invoices', 'invoice_id',
                           'facturacion:read', 'facturacion:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Contratos
-- ═══════════════════════════════════════════════════════════════════════════

create table public.contracts (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references public.organizations (id) on delete cascade,
  code         text,
  title        text not null check (length(btrim(title)) between 1 and 200),
  kind         text not null default 'Cliente'
                 check (kind in ('Cliente', 'Proveedor', 'Laboral', 'Arrendamiento',
                                 'Confidencialidad', 'Otro')),
  status       text not null default 'Borrador'
                 check (status in ('Borrador', 'Vigente', 'Por vencer', 'Vencido', 'Terminado')),
  counterparty text not null default '',
  client_id    uuid references public.clients (id) on delete set null,
  employee_id  uuid references public.employees (id) on delete set null,
  document_id  uuid references public.documents (id) on delete set null,
  owner_id     uuid references public.employees (id) on delete set null,
  value_cents  bigint not null default 0 check (value_cents >= 0),
  starts_on    date,
  ends_on      date,
  -- Days before `ends_on` at which the contract should start showing as "Por
  -- vencer". Per contract because a twelve-month lease and a two-week service
  -- agreement do not deserve the same warning.
  notice_days  smallint not null default 30 check (notice_days between 0 and 365),
  auto_renew   boolean not null default false,
  notes        text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz,
  unique (org_id, code),
  constraint contracts_dates_ordered check (ends_on is null or starts_on is null or ends_on >= starts_on)
);

create index contracts_org_idx on public.contracts (org_id, status) where deleted_at is null;
create index contracts_expiry_idx on public.contracts (org_id, ends_on)
  where deleted_at is null and status in ('Vigente', 'Por vencer');

create trigger contracts_code  before insert on public.contracts
  for each row execute function app.set_code('contract', 'CTR', '4');
create trigger contracts_touch before update on public.contracts
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('contracts', 'contratos:read', 'contratos:write');

create table public.contract_milestones (
  id           uuid primary key default gen_random_uuid(),
  contract_id  uuid not null references public.contracts (id) on delete cascade,
  title        text not null,
  due_on       date,
  amount_cents bigint not null default 0 check (amount_cents >= 0),
  completed_at timestamptz,
  position     smallint not null default 0
);

create index contract_milestones_contract_idx
  on public.contract_milestones (contract_id, position);

select app.apply_child_rls('contract_milestones', 'contracts', 'contract_id',
                           'contratos:read', 'contratos:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Reclutamiento
-- ═══════════════════════════════════════════════════════════════════════════

-- `job_openings` and `candidates` already exist (migration 02). Widened here
-- into a module rather than replaced: the FK column stays `job_opening_id`,
-- because renaming a column nothing has read yet is churn, and renaming one
-- something HAS read is a break.

alter table public.job_openings
  add column location text not null default '',
  add column openings smallint not null default 1 check (openings between 1 and 999),
  add column salary_min_cents bigint not null default 0 check (salary_min_cents >= 0),
  add column salary_max_cents bigint not null default 0 check (salary_max_cents >= 0),
  add column hiring_manager_id uuid references public.employees (id) on delete set null,
  add column description text not null default '',
  add column closed_on date,
  add column deleted_at timestamptz,
  add constraint job_openings_salary_ordered
    check (salary_max_cents = 0 or salary_max_cents >= salary_min_cents);

-- The old vocabulary ('Activo', 'Pausado', 'Cerrado') described whether the
-- posting was live. The new one describes where the search is, which is what
-- the board columns key off. Existing rows are mapped rather than left to
-- violate the new constraint — an ALTER that fails on real data is a migration
-- that only works on an empty database.
update public.job_openings set status = case status
  when 'Activo'  then 'Abierta'
  when 'Pausado' then 'En proceso'
  when 'Cerrado' then 'Cerrada'
  else status
end;

alter table public.job_openings
  drop constraint if exists job_openings_status_check;
alter table public.job_openings
  alter column status set default 'Abierta',
  add constraint job_openings_status_check
    check (status in ('Abierta', 'En proceso', 'Cerrada', 'Cancelada'));

create index job_openings_org_idx on public.job_openings (org_id, status)
  where deleted_at is null;

select app.repoint_standard_rls('job_openings', 'reclutamiento:read', 'reclutamiento:write');

alter table public.candidates
  add column phone text not null default '',
  add column rating smallint check (rating is null or rating between 1 and 5),
  add column expected_salary_cents bigint not null default 0
    check (expected_salary_cents >= 0),
  add column resume_url text,
  add column notes text not null default '',
  add column applied_on date not null default current_date,
  -- Set when the candidate reaches 'Contratado' and an employee row is created
  -- from them, so the funnel can report conversion without guessing by name.
  add column employee_id uuid references public.employees (id) on delete set null;

update public.candidates set stage = case stage
  when 'Aplicación' then 'Postulado'
  when 'Revisión'   then 'Preselección'
  else stage
end;

alter table public.candidates
  drop constraint if exists candidates_stage_check;
alter table public.candidates
  alter column stage set default 'Postulado',
  add constraint candidates_stage_check
    check (stage in ('Postulado', 'Preselección', 'Entrevista', 'Prueba',
                     'Oferta', 'Contratado', 'Descartado'));

select app.repoint_child_rls('candidates', 'job_openings', 'job_opening_id',
                             'reclutamiento:read', 'reclutamiento:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Capacitación
-- ═══════════════════════════════════════════════════════════════════════════

-- `courses`, `course_enrollments` and `certifications` already exist
-- (migration 02) under `empleados`. Widened and re-pointed at `capacitacion`.

alter table public.courses
  add column code text,
  add column mode text not null default 'Presencial'
    check (mode in ('Presencial', 'Virtual', 'Mixto')),
  add column provider text not null default '',
  add column instructor text not null default '',
  add column cost_cents bigint not null default 0 check (cost_cents >= 0),
  add column seats smallint check (seats is null or seats > 0),
  -- Courses that expire produce a recurring obligation: HSEQ and safety
  -- certifications are the reason this exists rather than a "completed" flag.
  add column validity_months smallint check (validity_months is null or validity_months > 0),
  add column is_mandatory boolean not null default false,
  add column starts_on date,
  add column ends_on date,
  add column description text not null default '',
  add column deleted_at timestamptz,
  add constraint courses_dates_ordered
    check (ends_on is null or starts_on is null or ends_on >= starts_on);

-- `duration_hours numeric(5,1)` is kept as it was rather than replaced by an
-- `hours` column: it already holds the right number under a clear name, and a
-- second column for the same quantity is how the two disagree later.
create unique index courses_org_code_key on public.courses (org_id, code)
  where code is not null;
create index courses_org_idx on public.courses (org_id) where deleted_at is null;

create trigger courses_code before insert on public.courses
  for each row execute function app.set_code('course', 'CUR', '4');

select app.repoint_standard_rls('courses', 'capacitacion:read', 'capacitacion:write');

alter table public.course_enrollments
  add column score numeric(5,2) check (score is null or score between 0 and 100),
  add column expires_on date,
  add column certificate_url text,
  add column created_at timestamptz not null default now(),
  add column updated_at timestamptz not null default now();

update public.course_enrollments set status = case status
  when 'Completado'  then 'Aprobado'
  when 'Abandonado'  then 'Cancelado'
  else status
end;

alter table public.course_enrollments
  drop constraint if exists course_enrollments_status_check;
alter table public.course_enrollments
  add constraint course_enrollments_status_check
    check (status in ('Inscrito', 'En curso', 'Aprobado', 'Reprobado', 'Cancelado'));

create index course_enrollments_employee_idx on public.course_enrollments (employee_id, status);
create index course_enrollments_expiry_idx on public.course_enrollments (expires_on)
  where expires_on is not null;

create trigger course_enrollments_touch before update on public.course_enrollments
  for each row execute function app.touch_updated_at();

select app.repoint_child_rls('course_enrollments', 'courses', 'course_id',
                             'capacitacion:read', 'capacitacion:write');

-- Certifications a person holds that did not come from an internal course —
-- a driving licence, a height-work card, a professional registration.
select app.repoint_standard_rls('certifications', 'capacitacion:read', 'capacitacion:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Desempeño
-- ═══════════════════════════════════════════════════════════════════════════

create table public.review_cycles (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references public.organizations (id) on delete cascade,
  name        text not null check (length(btrim(name)) between 1 and 120),
  status      text not null default 'Planificado'
                check (status in ('Planificado', 'Abierto', 'En calibración', 'Cerrado')),
  starts_on   date not null default current_date,
  ends_on     date,
  description text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz,
  constraint review_cycles_dates_ordered check (ends_on is null or ends_on >= starts_on)
);

create index review_cycles_org_idx on public.review_cycles (org_id, status) where deleted_at is null;

create trigger review_cycles_touch before update on public.review_cycles
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('review_cycles', 'desempeno:read', 'desempeno:write');

-- The review itself is `evaluations`, which migration 02 already created with
-- employee, evaluator, score and objective counts. It is widened and attached
-- to a cycle here rather than superseded by a new `performance_reviews`: a
-- second table for "how did this person do" would leave the answer split
-- across two, and the existing one already has the columns that matter.
--
-- Its status vocabulary is extended, not replaced. 'Pendiente', 'En revisión'
-- and 'Completada' stay valid, so no existing row needs rewriting and no
-- ALTER can fail on live data.
alter table public.evaluations
  add column cycle_id uuid references public.review_cycles (id) on delete set null,
  add column strengths text not null default '',
  add column improvements text not null default '',
  add column comments text not null default '',
  add column submitted_at timestamptz,
  add column deleted_at timestamptz;

alter table public.evaluations
  drop constraint if exists evaluations_status_check;
alter table public.evaluations
  add constraint evaluations_status_check
    check (status in ('Pendiente', 'En revisión', 'Completada', 'Calibrada'));

create index evaluations_cycle_idx on public.evaluations (cycle_id)
  where deleted_at is null;
create index evaluations_employee_idx on public.evaluations (employee_id)
  where deleted_at is null;

select app.repoint_standard_rls('evaluations', 'desempeno:read', 'desempeno:write');

-- Goals are org-level rather than a child of a cycle: an objective can outlive
-- the review it was set in, and a company that runs no formal cycles still
-- wants to track them.
create table public.employee_goals (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references public.organizations (id) on delete cascade,
  employee_id  uuid not null references public.employees (id) on delete cascade,
  cycle_id     uuid references public.review_cycles (id) on delete set null,
  title        text not null check (length(btrim(title)) between 1 and 200),
  detail       text not null default '',
  metric       text not null default '',
  target_value numeric(14,2),
  current_value numeric(14,2) not null default 0,
  weight       smallint not null default 0 check (weight between 0 and 100),
  status       text not null default 'En progreso'
                 check (status in ('En progreso', 'Cumplido', 'No cumplido', 'Cancelado')),
  due_on       date,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz
);

create index employee_goals_org_idx on public.employee_goals (org_id, status) where deleted_at is null;
create index employee_goals_employee_idx on public.employee_goals (employee_id) where deleted_at is null;

create trigger employee_goals_touch before update on public.employee_goals
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('employee_goals', 'desempeno:read', 'desempeno:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Mantenimiento
--
-- Work orders point at an inventory asset when there is one and carry free
-- text when there is not: a company can run maintenance without having built
-- its asset register first, and forcing the FK would make the module unusable
-- until it had.
-- ═══════════════════════════════════════════════════════════════════════════

create table public.work_orders (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references public.organizations (id) on delete cascade,
  code          text,
  title         text not null check (length(btrim(title)) between 1 and 200),
  kind          text not null default 'Correctivo'
                  check (kind in ('Preventivo', 'Correctivo', 'Predictivo', 'Mejora')),
  status        text not null default 'Abierta'
                  check (status in ('Abierta', 'Programada', 'En ejecución', 'Completada', 'Cancelada')),
  priority      text not null default 'Media' check (priority in ('Alta', 'Media', 'Baja')),
  asset_id      uuid references public.inventory_assets (id) on delete set null,
  asset_label   text not null default '',
  project_id    uuid references public.projects (id) on delete set null,
  assignee_id   uuid references public.employees (id) on delete set null,
  location      text not null default '',
  detail        text not null default '',
  scheduled_on  date,
  completed_at  timestamptz,
  downtime_hours numeric(8,2) not null default 0 check (downtime_hours >= 0),
  labor_cost_cents bigint not null default 0 check (labor_cost_cents >= 0),
  parts_cost_cents bigint not null default 0 check (parts_cost_cents >= 0),
  -- Preventive work repeats. Null means one-off; the module reads this to
  -- offer "programar la siguiente" when the order is completed.
  recurrence_days smallint check (recurrence_days is null or recurrence_days > 0),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,
  unique (org_id, code)
);

create index work_orders_org_idx on public.work_orders (org_id, status) where deleted_at is null;
create index work_orders_asset_idx on public.work_orders (asset_id) where deleted_at is null;
create index work_orders_scheduled_idx on public.work_orders (org_id, scheduled_on)
  where deleted_at is null and status in ('Abierta', 'Programada');

create trigger work_orders_code  before insert on public.work_orders
  for each row execute function app.set_code('work_order', 'OT', '5');
create trigger work_orders_touch before update on public.work_orders
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('work_orders', 'mantenimiento:read', 'mantenimiento:write');

create table public.work_order_tasks (
  id            uuid primary key default gen_random_uuid(),
  work_order_id uuid not null references public.work_orders (id) on delete cascade,
  description   text not null,
  done          boolean not null default false,
  position      smallint not null default 0
);

create index work_order_tasks_order_idx on public.work_order_tasks (work_order_id, position);

select app.apply_child_rls('work_order_tasks', 'work_orders', 'work_order_id',
                           'mantenimiento:read', 'mantenimiento:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Flota
-- ═══════════════════════════════════════════════════════════════════════════

create table public.vehicles (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references public.organizations (id) on delete cascade,
  plate         text not null check (length(btrim(plate)) between 1 and 20),
  kind          text not null default 'Camioneta'
                  check (kind in ('Automóvil', 'Camioneta', 'Camión', 'Motocicleta', 'Maquinaria', 'Otro')),
  brand         text not null default '',
  model         text not null default '',
  model_year    smallint check (model_year is null or model_year between 1950 and 2100),
  fuel          text not null default 'Gasolina'
                  check (fuel in ('Gasolina', 'Diésel', 'Gas', 'Eléctrico', 'Híbrido')),
  status        text not null default 'Disponible'
                  check (status in ('Disponible', 'En ruta', 'En taller', 'Fuera de servicio', 'Dado de baja')),
  driver_id     uuid references public.employees (id) on delete set null,
  odometer_km   int not null default 0 check (odometer_km >= 0),
  capacity_kg   int check (capacity_kg is null or capacity_kg >= 0),
  -- The three documents that ground a vehicle in Colombia when they lapse. The
  -- module's whole reason to exist is answering "what expires this month".
  soat_expires_on      date,
  inspection_expires_on date,
  insurance_expires_on date,
  notes         text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,
  unique (org_id, plate)
);

create index vehicles_org_idx on public.vehicles (org_id, status) where deleted_at is null;

create trigger vehicles_touch before update on public.vehicles
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('vehicles', 'flota:read', 'flota:write');

create table public.vehicle_services (
  id           uuid primary key default gen_random_uuid(),
  vehicle_id   uuid not null references public.vehicles (id) on delete cascade,
  kind         text not null default 'Preventivo'
                 check (kind in ('Preventivo', 'Correctivo', 'Predictivo', 'Mejora')),
  description  text not null default '',
  provider     text not null default '',
  odometer_km  int check (odometer_km is null or odometer_km >= 0),
  cost_cents   bigint not null default 0 check (cost_cents >= 0),
  serviced_on  date not null default current_date,
  next_service_on date,
  created_at   timestamptz not null default now()
);

create index vehicle_services_vehicle_idx on public.vehicle_services (vehicle_id, serviced_on desc);

select app.apply_child_rls('vehicle_services', 'vehicles', 'vehicle_id',
                           'flota:read', 'flota:write');

create table public.fuel_logs (
  id           uuid primary key default gen_random_uuid(),
  vehicle_id   uuid not null references public.vehicles (id) on delete cascade,
  liters       numeric(9,2) not null check (liters > 0),
  cost_cents   bigint not null default 0 check (cost_cents >= 0),
  odometer_km  int check (odometer_km is null or odometer_km >= 0),
  station      text not null default '',
  driver_id    uuid references public.employees (id) on delete set null,
  filled_on    date not null default current_date,
  created_at   timestamptz not null default now()
);

create index fuel_logs_vehicle_idx on public.fuel_logs (vehicle_id, filled_on desc);

select app.apply_child_rls('fuel_logs', 'vehicles', 'vehicle_id',
                           'flota:read', 'flota:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Producción
-- ═══════════════════════════════════════════════════════════════════════════

create table public.production_orders (
  id             uuid primary key default gen_random_uuid(),
  org_id         uuid not null references public.organizations (id) on delete cascade,
  code           text,
  product_id     uuid references public.products (id) on delete set null,
  product_label  text not null default '',
  status         text not null default 'Planificada'
                   check (status in ('Planificada', 'En proceso', 'En pausa', 'Terminada', 'Cancelada')),
  quantity_planned numeric(12,2) not null check (quantity_planned > 0),
  quantity_done  numeric(12,2) not null default 0 check (quantity_done >= 0),
  quantity_scrap numeric(12,2) not null default 0 check (quantity_scrap >= 0),
  unit           text not null default 'UN',
  line           text not null default '',
  supervisor_id  uuid references public.employees (id) on delete set null,
  starts_on      date,
  due_on         date,
  completed_at   timestamptz,
  cost_cents     bigint not null default 0 check (cost_cents >= 0),
  notes          text not null default '',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz,
  unique (org_id, code),
  constraint production_orders_dates_ordered
    check (due_on is null or starts_on is null or due_on >= starts_on)
);

create index production_orders_org_idx on public.production_orders (org_id, status)
  where deleted_at is null;

create trigger production_orders_code  before insert on public.production_orders
  for each row execute function app.set_code('production_order', 'OP', '5');
create trigger production_orders_touch before update on public.production_orders
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('production_orders', 'produccion:read', 'produccion:write');

create table public.production_stages (
  id            uuid primary key default gen_random_uuid(),
  order_id      uuid not null references public.production_orders (id) on delete cascade,
  name          text not null,
  status        text not null default 'Planificada'
                  check (status in ('Planificada', 'En proceso', 'En pausa', 'Terminada', 'Cancelada')),
  quantity_done numeric(12,2) not null default 0 check (quantity_done >= 0),
  operator_id   uuid references public.employees (id) on delete set null,
  started_at    timestamptz,
  finished_at   timestamptz,
  position      smallint not null default 0
);

create index production_stages_order_idx on public.production_stages (order_id, position);

select app.apply_child_rls('production_stages', 'production_orders', 'order_id',
                           'produccion:read', 'produccion:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Ecommerce
--
-- Distinct from `tienda`, which is the internal catalogue-and-cart an employee
-- uses to raise an order. This is what the public buys: an order that arrived
-- with a shipping address, a payment state and a courier.
-- ═══════════════════════════════════════════════════════════════════════════

create table public.online_orders (
  id             uuid primary key default gen_random_uuid(),
  org_id         uuid not null references public.organizations (id) on delete cascade,
  code           text,
  client_id      uuid references public.clients (id) on delete set null,
  customer_name  text not null default '',
  customer_email text check (customer_email is null or customer_email = lower(customer_email)),
  customer_phone text not null default '',
  status         text not null default 'Nuevo'
                   check (status in ('Nuevo', 'Pagado', 'En preparación', 'Enviado',
                                     'Entregado', 'Cancelado', 'Devuelto')),
  shipping_method text not null default 'Domicilio'
                   check (shipping_method in ('Domicilio', 'Recoge en tienda', 'Mensajería', 'Otro')),
  shipping_address text not null default '',
  shipping_city  text not null default '',
  tracking_code  text not null default '',
  subtotal_cents bigint not null default 0 check (subtotal_cents >= 0),
  shipping_cents bigint not null default 0 check (shipping_cents >= 0),
  discount_cents bigint not null default 0 check (discount_cents >= 0),
  total_cents    bigint not null default 0 check (total_cents >= 0),
  coupon_code    text not null default '',
  placed_at      timestamptz not null default now(),
  shipped_at     timestamptz,
  delivered_at   timestamptz,
  notes          text not null default '',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz,
  unique (org_id, code)
);

create index online_orders_org_idx on public.online_orders (org_id, status) where deleted_at is null;
create index online_orders_placed_idx on public.online_orders (org_id, placed_at desc)
  where deleted_at is null;

create trigger online_orders_code  before insert on public.online_orders
  for each row execute function app.set_code('online_order', 'PED', '5');
create trigger online_orders_touch before update on public.online_orders
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('online_orders', 'ecommerce:read', 'ecommerce:write');

create table public.online_order_items (
  id            uuid primary key default gen_random_uuid(),
  order_id      uuid not null references public.online_orders (id) on delete cascade,
  product_id    uuid references public.products (id) on delete set null,
  description   text not null,
  quantity      numeric(12,2) not null default 1 check (quantity > 0),
  unit_price_cents bigint not null default 0 check (unit_price_cents >= 0),
  position      smallint not null default 0
);

create index online_order_items_order_idx on public.online_order_items (order_id, position);

select app.apply_child_rls('online_order_items', 'online_orders', 'order_id',
                           'ecommerce:read', 'ecommerce:write');

create table public.discount_coupons (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references public.organizations (id) on delete cascade,
  code          text not null check (code = upper(code) and length(btrim(code)) between 3 and 32),
  -- Exactly one of the two applies, which is why they are separate columns
  -- with a constraint rather than an amount plus a "kind" the UI must decode.
  percent_off   smallint check (percent_off is null or percent_off between 1 and 100),
  amount_off_cents bigint check (amount_off_cents is null or amount_off_cents > 0),
  min_total_cents bigint not null default 0 check (min_total_cents >= 0),
  max_uses      int check (max_uses is null or max_uses > 0),
  used_count    int not null default 0 check (used_count >= 0),
  starts_on     date,
  expires_on    date,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (org_id, code),
  constraint discount_coupons_one_kind check (
    (percent_off is not null and amount_off_cents is null)
    or (percent_off is null and amount_off_cents is not null)
  )
);

create trigger discount_coupons_touch before update on public.discount_coupons
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('discount_coupons', 'ecommerce:read', 'ecommerce:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Pacientes
--
-- Clinical data. Every column here is health information about an identified
-- person, so the module carries its own permission pair and nothing grants it
-- to the Empleado role by default — see migration 14.
-- ═══════════════════════════════════════════════════════════════════════════

create table public.patients (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references public.organizations (id) on delete cascade,
  code          text,
  full_name     text not null check (length(btrim(full_name)) between 1 and 160),
  document_id   text not null default '',
  birth_date    date,
  sex           text check (sex is null or sex in ('F', 'M', 'Otro')),
  blood_type    text check (blood_type is null or blood_type in
                  ('O+', 'O-', 'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-')),
  status        text not null default 'Activo'
                  check (status in ('Activo', 'Inactivo', 'Egresado')),
  email         text check (email is null or email = lower(email)),
  phone         text not null default '',
  address       text not null default '',
  insurer       text not null default '',
  allergies     text not null default '',
  conditions    text not null default '',
  emergency_contact text not null default '',
  emergency_phone   text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,
  unique (org_id, code)
);

create index patients_org_idx on public.patients (org_id, status) where deleted_at is null;

create trigger patients_code  before insert on public.patients
  for each row execute function app.set_code('patient', 'PAC', '5');
create trigger patients_touch before update on public.patients
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('patients', 'pacientes:read', 'pacientes:write');

create table public.patient_visits (
  id           uuid primary key default gen_random_uuid(),
  patient_id   uuid not null references public.patients (id) on delete cascade,
  kind         text not null default 'Consulta'
                 check (kind in ('Consulta', 'Control', 'Urgencia', 'Procedimiento', 'Teleconsulta')),
  professional_id uuid references public.employees (id) on delete set null,
  reason       text not null default '',
  diagnosis    text not null default '',
  treatment    text not null default '',
  notes        text not null default '',
  fee_cents    bigint not null default 0 check (fee_cents >= 0),
  visited_at   timestamptz not null default now(),
  follow_up_on date,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index patient_visits_patient_idx on public.patient_visits (patient_id, visited_at desc);

create trigger patient_visits_touch before update on public.patient_visits
  for each row execute function app.touch_updated_at();

select app.apply_child_rls('patient_visits', 'patients', 'patient_id',
                           'pacientes:read', 'pacientes:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Estudiantes
-- ═══════════════════════════════════════════════════════════════════════════

create table public.academic_programs (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references public.organizations (id) on delete cascade,
  code         text,
  name         text not null check (length(btrim(name)) between 1 and 160),
  level        text not null default '',
  duration_terms smallint check (duration_terms is null or duration_terms > 0),
  tuition_cents bigint not null default 0 check (tuition_cents >= 0),
  coordinator_id uuid references public.employees (id) on delete set null,
  description  text not null default '',
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz,
  unique (org_id, code)
);

create index academic_programs_org_idx on public.academic_programs (org_id) where deleted_at is null;

create trigger academic_programs_code  before insert on public.academic_programs
  for each row execute function app.set_code('academic_program', 'PRG', '3');
create trigger academic_programs_touch before update on public.academic_programs
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('academic_programs', 'estudiantes:read', 'estudiantes:write');

create table public.students (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references public.organizations (id) on delete cascade,
  code          text,
  full_name     text not null check (length(btrim(full_name)) between 1 and 160),
  document_id   text not null default '',
  birth_date    date,
  email         text check (email is null or email = lower(email)),
  phone         text not null default '',
  address       text not null default '',
  status        text not null default 'Activo'
                  check (status in ('Activo', 'Retirado', 'Graduado', 'Suspendido')),
  program_id    uuid references public.academic_programs (id) on delete set null,
  guardian_name text not null default '',
  guardian_phone text not null default '',
  enrolled_on   date not null default current_date,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,
  unique (org_id, code)
);

create index students_org_idx on public.students (org_id, status) where deleted_at is null;
create index students_program_idx on public.students (program_id) where deleted_at is null;

create trigger students_code  before insert on public.students
  for each row execute function app.set_code('student', 'EST', '5');
create trigger students_touch before update on public.students
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('students', 'estudiantes:read', 'estudiantes:write');

create table public.student_enrollments (
  id          uuid primary key default gen_random_uuid(),
  student_id  uuid not null references public.students (id) on delete cascade,
  subject     text not null,
  term        text not null default '',
  teacher_id  uuid references public.employees (id) on delete set null,
  status      text not null default 'Inscrito'
                check (status in ('Inscrito', 'Cursando', 'Aprobado', 'Reprobado', 'Retirado')),
  grade       numeric(4,2) check (grade is null or grade between 0 and 100),
  attendance_pct smallint check (attendance_pct is null or attendance_pct between 0 and 100),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (student_id, subject, term)
);

create index student_enrollments_student_idx on public.student_enrollments (student_id);

create trigger student_enrollments_touch before update on public.student_enrollments
  for each row execute function app.touch_updated_at();

select app.apply_child_rls('student_enrollments', 'students', 'student_id',
                           'estudiantes:read', 'estudiantes:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Restaurante
-- ═══════════════════════════════════════════════════════════════════════════

create table public.menu_items (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references public.organizations (id) on delete cascade,
  name         text not null check (length(btrim(name)) between 1 and 160),
  category     text not null default 'Plato fuerte'
                 check (category in ('Entrada', 'Plato fuerte', 'Postre', 'Bebida', 'Cóctel', 'Otro')),
  description  text not null default '',
  price_cents  bigint not null default 0 check (price_cents >= 0),
  cost_cents   bigint not null default 0 check (cost_cents >= 0),
  prep_minutes smallint check (prep_minutes is null or prep_minutes >= 0),
  allergens    text not null default '',
  is_available boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz
);

create index menu_items_org_idx on public.menu_items (org_id, category) where deleted_at is null;

create trigger menu_items_touch before update on public.menu_items
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('menu_items', 'restaurante:read', 'restaurante:write');

create table public.dining_tables (
  id         uuid primary key default gen_random_uuid(),
  org_id     uuid not null references public.organizations (id) on delete cascade,
  label      text not null check (length(btrim(label)) between 1 and 40),
  zone       text not null default '',
  seats      smallint not null default 2 check (seats between 1 and 100),
  status     text not null default 'Libre'
               check (status in ('Libre', 'Ocupada', 'Reservada', 'Fuera de servicio')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (org_id, label)
);

create trigger dining_tables_touch before update on public.dining_tables
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('dining_tables', 'restaurante:read', 'restaurante:write');

create table public.restaurant_orders (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references public.organizations (id) on delete cascade,
  code        text,
  table_id    uuid references public.dining_tables (id) on delete set null,
  waiter_id   uuid references public.employees (id) on delete set null,
  status      text not null default 'Abierta'
                check (status in ('Abierta', 'En cocina', 'Servida', 'Pagada', 'Anulada')),
  guests      smallint not null default 1 check (guests between 1 and 200),
  subtotal_cents bigint not null default 0 check (subtotal_cents >= 0),
  tip_cents   bigint not null default 0 check (tip_cents >= 0),
  total_cents bigint not null default 0 check (total_cents >= 0),
  opened_at   timestamptz not null default now(),
  closed_at   timestamptz,
  notes       text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz,
  unique (org_id, code)
);

create index restaurant_orders_org_idx on public.restaurant_orders (org_id, status)
  where deleted_at is null;

create trigger restaurant_orders_code  before insert on public.restaurant_orders
  for each row execute function app.set_code('restaurant_order', 'CMD', '5');
create trigger restaurant_orders_touch before update on public.restaurant_orders
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('restaurant_orders', 'restaurante:read', 'restaurante:write');

create table public.restaurant_order_items (
  id           uuid primary key default gen_random_uuid(),
  order_id     uuid not null references public.restaurant_orders (id) on delete cascade,
  menu_item_id uuid references public.menu_items (id) on delete set null,
  description  text not null,
  quantity     smallint not null default 1 check (quantity > 0),
  unit_price_cents bigint not null default 0 check (unit_price_cents >= 0),
  notes        text not null default '',
  position     smallint not null default 0
);

create index restaurant_order_items_order_idx on public.restaurant_order_items (order_id, position);

select app.apply_child_rls('restaurant_order_items', 'restaurant_orders', 'order_id',
                           'restaurante:read', 'restaurante:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Agro
-- ═══════════════════════════════════════════════════════════════════════════

create table public.farm_lots (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references public.organizations (id) on delete cascade,
  code        text,
  name        text not null check (length(btrim(name)) between 1 and 160),
  farm        text not null default '',
  hectares    numeric(10,2) not null default 0 check (hectares >= 0),
  soil_type   text not null default '',
  location    text not null default '',
  status      text not null default 'Disponible'
                check (status in ('Disponible', 'Sembrado', 'En cosecha', 'En descanso')),
  notes       text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz,
  unique (org_id, code)
);

create index farm_lots_org_idx on public.farm_lots (org_id, status) where deleted_at is null;

create trigger farm_lots_code  before insert on public.farm_lots
  for each row execute function app.set_code('farm_lot', 'LOT', '4');
create trigger farm_lots_touch before update on public.farm_lots
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('farm_lots', 'agro:read', 'agro:write');

-- Cycles carry their own org_id rather than inheriting through the lot: they
-- are the row the module lists, filters and paginates, and a child policy
-- would make every one of those queries a join.
create table public.crop_cycles (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references public.organizations (id) on delete cascade,
  lot_id        uuid not null references public.farm_lots (id) on delete cascade,
  crop          text not null check (length(btrim(crop)) between 1 and 120),
  variety       text not null default '',
  status        text not null default 'Planificado'
                  check (status in ('Planificado', 'Sembrado', 'En crecimiento', 'Cosechado', 'Perdido')),
  hectares      numeric(10,2) not null default 0 check (hectares >= 0),
  sown_on       date,
  expected_harvest_on date,
  expected_yield_kg numeric(12,2) check (expected_yield_kg is null or expected_yield_kg >= 0),
  input_cost_cents bigint not null default 0 check (input_cost_cents >= 0),
  responsible_id uuid references public.employees (id) on delete set null,
  notes         text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz
);

create index crop_cycles_org_idx on public.crop_cycles (org_id, status) where deleted_at is null;
create index crop_cycles_lot_idx on public.crop_cycles (lot_id) where deleted_at is null;

create trigger crop_cycles_touch before update on public.crop_cycles
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('crop_cycles', 'agro:read', 'agro:write');

create table public.harvests (
  id            uuid primary key default gen_random_uuid(),
  cycle_id      uuid not null references public.crop_cycles (id) on delete cascade,
  quantity_kg   numeric(12,2) not null check (quantity_kg >= 0),
  quality       text not null default '',
  price_per_kg_cents bigint not null default 0 check (price_per_kg_cents >= 0),
  buyer         text not null default '',
  harvested_on  date not null default current_date,
  notes         text not null default '',
  created_at    timestamptz not null default now()
);

create index harvests_cycle_idx on public.harvests (cycle_id, harvested_on desc);

select app.apply_child_rls('harvests', 'crop_cycles', 'cycle_id',
                           'agro:read', 'agro:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Inmobiliario
-- ═══════════════════════════════════════════════════════════════════════════

create table public.properties (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references public.organizations (id) on delete cascade,
  code         text,
  name         text not null check (length(btrim(name)) between 1 and 160),
  kind         text not null default 'Apartamento'
                 check (kind in ('Apartamento', 'Casa', 'Oficina', 'Local', 'Bodega', 'Lote')),
  status       text not null default 'Disponible'
                 check (status in ('Disponible', 'Arrendado', 'En mantenimiento', 'Vendido')),
  address      text not null default '',
  city         text not null default '',
  area_m2      numeric(10,2) check (area_m2 is null or area_m2 >= 0),
  bedrooms     smallint check (bedrooms is null or bedrooms >= 0),
  bathrooms    smallint check (bathrooms is null or bathrooms >= 0),
  parking_spots smallint check (parking_spots is null or parking_spots >= 0),
  rent_cents   bigint not null default 0 check (rent_cents >= 0),
  admin_fee_cents bigint not null default 0 check (admin_fee_cents >= 0),
  sale_price_cents bigint not null default 0 check (sale_price_cents >= 0),
  owner_name   text not null default '',
  notes        text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz,
  unique (org_id, code)
);

create index properties_org_idx on public.properties (org_id, status) where deleted_at is null;

create trigger properties_code  before insert on public.properties
  for each row execute function app.set_code('property', 'INM', '4');
create trigger properties_touch before update on public.properties
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('properties', 'inmobiliario:read', 'inmobiliario:write');

create table public.leases (
  id             uuid primary key default gen_random_uuid(),
  org_id         uuid not null references public.organizations (id) on delete cascade,
  property_id    uuid not null references public.properties (id) on delete cascade,
  tenant_name    text not null check (length(btrim(tenant_name)) between 1 and 160),
  tenant_document text not null default '',
  tenant_email   text check (tenant_email is null or tenant_email = lower(tenant_email)),
  tenant_phone   text not null default '',
  client_id      uuid references public.clients (id) on delete set null,
  contract_id    uuid references public.contracts (id) on delete set null,
  status         text not null default 'Activo'
                   check (status in ('Activo', 'Por vencer', 'Terminado', 'En mora')),
  rent_cents     bigint not null default 0 check (rent_cents >= 0),
  deposit_cents  bigint not null default 0 check (deposit_cents >= 0),
  -- Day of the month rent falls due. Drives the "quién debe este mes" list,
  -- which is the question the module exists to answer.
  due_day        smallint not null default 5 check (due_day between 1 and 28),
  starts_on      date not null default current_date,
  ends_on        date,
  notes          text not null default '',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz,
  constraint leases_dates_ordered check (ends_on is null or ends_on >= starts_on)
);

create index leases_org_idx on public.leases (org_id, status) where deleted_at is null;
create index leases_property_idx on public.leases (property_id) where deleted_at is null;

create trigger leases_touch before update on public.leases
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('leases', 'inmobiliario:read', 'inmobiliario:write');

create table public.lease_payments (
  id           uuid primary key default gen_random_uuid(),
  lease_id     uuid not null references public.leases (id) on delete cascade,
  period       text not null check (period ~ '^\d{4}-\d{2}$'),
  amount_cents bigint not null check (amount_cents >= 0),
  paid_cents   bigint not null default 0 check (paid_cents >= 0),
  due_on       date not null,
  paid_on      date,
  method       text not null default 'Transferencia'
                 check (method in ('Transferencia', 'Efectivo', 'Tarjeta', 'Cheque', 'Otro')),
  reference    text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  -- One row per lease per month. Two payments for March is a data-entry
  -- mistake, and without this the arrears report double counts.
  unique (lease_id, period)
);

create index lease_payments_lease_idx on public.lease_payments (lease_id, due_on desc);

create trigger lease_payments_touch before update on public.lease_payments
  for each row execute function app.touch_updated_at();

select app.apply_child_rls('lease_payments', 'leases', 'lease_id',
                           'inmobiliario:read', 'inmobiliario:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Hotelería
-- ═══════════════════════════════════════════════════════════════════════════

create table public.hotel_rooms (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references public.organizations (id) on delete cascade,
  number       text not null check (length(btrim(number)) between 1 and 20),
  kind         text not null default 'Sencilla'
                 check (kind in ('Sencilla', 'Doble', 'Triple', 'Suite', 'Familiar')),
  status       text not null default 'Disponible'
                 check (status in ('Disponible', 'Ocupada', 'Limpieza', 'Mantenimiento', 'Bloqueada')),
  floor        smallint,
  capacity     smallint not null default 2 check (capacity between 1 and 20),
  rate_cents   bigint not null default 0 check (rate_cents >= 0),
  amenities    text not null default '',
  notes        text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz,
  unique (org_id, number)
);

create index hotel_rooms_org_idx on public.hotel_rooms (org_id, status) where deleted_at is null;

create trigger hotel_rooms_touch before update on public.hotel_rooms
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('hotel_rooms', 'hoteleria:read', 'hoteleria:write');

create table public.reservations (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references public.organizations (id) on delete cascade,
  code          text,
  room_id       uuid not null references public.hotel_rooms (id) on delete cascade,
  guest_name    text not null check (length(btrim(guest_name)) between 1 and 160),
  guest_document text not null default '',
  guest_email   text check (guest_email is null or guest_email = lower(guest_email)),
  guest_phone   text not null default '',
  client_id     uuid references public.clients (id) on delete set null,
  status        text not null default 'Confirmada'
                  check (status in ('Confirmada', 'Check-in', 'Check-out', 'Cancelada', 'No show')),
  guests        smallint not null default 1 check (guests between 1 and 20),
  checkin_on    date not null,
  checkout_on   date not null,
  nightly_rate_cents bigint not null default 0 check (nightly_rate_cents >= 0),
  total_cents   bigint not null default 0 check (total_cents >= 0),
  paid_cents    bigint not null default 0 check (paid_cents >= 0),
  channel       text not null default '',
  notes         text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,
  unique (org_id, code),
  -- A zero-night stay is not a reservation, so the checkout must be strictly
  -- after the checkin rather than merely not before it.
  constraint reservations_nights_positive check (checkout_on > checkin_on)
);

create index reservations_org_idx on public.reservations (org_id, status) where deleted_at is null;
create index reservations_room_dates_idx on public.reservations (room_id, checkin_on, checkout_on)
  where deleted_at is null;

create trigger reservations_code  before insert on public.reservations
  for each row execute function app.set_code('reservation', 'RES', '5');
create trigger reservations_touch before update on public.reservations
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('reservations', 'hoteleria:read', 'hoteleria:write');

-- ═══════════════════════════════════════════════════════════════════════════
-- Privileges
--
-- Nothing to do. Migration 08 set `alter default privileges in schema public`,
-- so every table created above already denies `anon`, grants DML to
-- `authenticated` and full access to `service_role` — and RLS, applied per
-- table above, is what actually filters the rows.
--
-- A blanket `grant ... on all tables in schema public to authenticated` was
-- here and has been removed: it would have re-granted INSERT/UPDATE/DELETE on
-- `public.roles`, `public.permissions` and `public.audit_log`, which migration
-- 08 revokes on purpose. Widening privileges on the permission catalogue as a
-- side effect of adding unrelated tables is exactly the kind of drift the
-- explicit-grants approach in 08 exists to prevent.
-- ═══════════════════════════════════════════════════════════════════════════
