-- ═══════════════════════════════════════════════════════════════════════════
-- 25 — Depth for the restaurante sector: reservas, costeo, caja y domicilios
--
-- The module shipped with the three things that happen at a table: the menu
-- (`menu_items`), the room (`dining_tables`) and the order (`restaurant_orders`
-- + items). That is a point-of-sale for the floor and nothing else, and it
-- leaves four questions a restaurant actually runs on unanswerable:
--
--   · who is coming tonight, and to which table   → `restaurant_reservations`
--   · what does this dish cost us to make         → `menu_item_ingredients`
--   · did the till match the sales at closing     → `cash_sessions`
--   · where is the order that left the building   → `restaurant_deliveries`
--
-- The four are one migration because they are one gap — «restaurante» was the
-- only sector module the 16–23 round skipped entirely, and shipping a quarter
-- of it would leave the same hole with more moving parts.
--
-- Every table stays inside the module's existing permission pair
-- (`restaurante:read` / `restaurante:write`). A sector gets a sector module,
-- not a cabinet of half-modules — the same rule migration 16 set for salud.
--
-- Conventions inherited from 02/03/15: money is bigint minor units, soft
-- delete on anything a user can remove by mistake, line items hard-deleted
-- with their parent, check constraints in the exact vocabulary the UI renders
-- (src/lib/domain.ts), and RLS generated by app.apply_standard_rls /
-- app.apply_child_rls rather than hand-written per table.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── Reservas ───────────────────────────────────────────────────────────────
-- A top-level entity, not a child of `dining_tables`: a booking is taken
-- before anyone decides which table it gets, and it must survive that table
-- being taken out of service. So the table is a nullable pointer, set null on
-- delete, and the reservation stays a fact about the evening.

create table public.restaurant_reservations (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references public.organizations (id) on delete cascade,
  code         text,
  table_id     uuid references public.dining_tables (id) on delete set null,
  guest_name   text not null check (length(btrim(guest_name)) between 1 and 160),
  guest_phone  text not null default '',
  party_size   smallint not null default 2 check (party_size between 1 and 200),
  -- Date and time kept in one timestamptz: a booking is an instant, and
  -- splitting it into a date plus a time column is how "8pm" ends up meaning
  -- two different moments either side of a timezone change.
  reserved_at  timestamptz not null,
  status       text not null default 'Confirmada'
                 check (status in ('Confirmada', 'Sentada', 'Cumplida', 'Cancelada', 'No show')),
  -- Set when the party is seated and the booking becomes an order, so the
  -- evening's covers can be traced from the phone call to the bill.
  order_id     uuid references public.restaurant_orders (id) on delete set null,
  notes        text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz,
  unique (org_id, code)
);

create index restaurant_reservations_when_idx
  on public.restaurant_reservations (org_id, reserved_at desc) where deleted_at is null;

create trigger restaurant_reservations_code before insert on public.restaurant_reservations
  for each row execute function app.set_code('restaurant_reservation', 'RSV', '5');
create trigger restaurant_reservations_touch before update on public.restaurant_reservations
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('restaurant_reservations', 'restaurante:read', 'restaurante:write');

comment on table public.restaurant_reservations is
  'Table bookings. Top-level: a reservation exists before a table is assigned and outlives it.';

-- ─── Costeo: los insumos de cada plato ──────────────────────────────────────
-- `menu_items.cost_cents` already existed and was typed in by hand — a number
-- nobody could check and nobody updated when the price of cheese moved. The
-- recipe is what makes it checkable: cost per dish becomes the sum of what
-- goes into it, and food cost (cost ÷ price) becomes a figure the module can
-- actually report instead of a claim.

create table public.menu_item_ingredients (
  id            uuid primary key default gen_random_uuid(),
  menu_item_id  uuid not null references public.menu_items (id) on delete cascade,
  name          text not null check (length(btrim(name)) between 1 and 120),
  quantity      numeric(12,3) not null default 1 check (quantity > 0),
  unit          text not null default 'g'
                  check (unit in ('g', 'kg', 'ml', 'L', 'UN', 'Porción')),
  -- Cost of the quantity above, not of one unit. A recipe line is "200 g of
  -- salmon costs 4.800", and storing a unit price would force every reader to
  -- redo the multiplication — including the trigger below, which is where a
  -- rounding disagreement would become a wrong menu cost.
  cost_cents    bigint not null default 0 check (cost_cents >= 0),
  created_at    timestamptz not null default now()
);

create index menu_item_ingredients_item_idx
  on public.menu_item_ingredients (menu_item_id);

select app.apply_child_rls('menu_item_ingredients', 'menu_items', 'menu_item_id',
                           'restaurante:read', 'restaurante:write');

/**
 * The dish costs what its recipe costs.
 *
 * Derived rather than typed, so the two can never disagree — a menu that
 * prices a dish off a stale cost is the exact failure this table exists to
 * stop. The rule has one deliberate exception: a dish with *no* recipe keeps
 * whatever `cost_cents` was entered by hand. Recalculating that to zero would
 * wipe the figures of every restaurant that has not sat down to enter recipes
 * yet, which is all of them the day this ships.
 */
create or replace function app.sync_menu_item_cost()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item  uuid;
  v_total bigint;
  v_lines int;
begin
  v_item := coalesce(new.menu_item_id, old.menu_item_id);

  select coalesce(sum(i.cost_cents), 0), count(*)
    into v_total, v_lines
  from public.menu_item_ingredients i
  where i.menu_item_id = v_item;

  -- The last ingredient being deleted returns the dish to hand-entered
  -- costing rather than silently zeroing it.
  if v_lines > 0 then
    update public.menu_items m set cost_cents = v_total where m.id = v_item;
  end if;

  return null;
end;
$$;

revoke all on function app.sync_menu_item_cost() from public, anon, authenticated;

create trigger menu_item_ingredients_sync_cost
  after insert or update or delete on public.menu_item_ingredients
  for each row execute function app.sync_menu_item_cost();

-- ─── Caja: turnos y arqueo ──────────────────────────────────────────────────
-- What the owner checks every night. A session opens with a float, collects
-- the orders paid while it is open, and closes against what was counted in the
-- drawer.

create table public.cash_sessions (
  id                  uuid primary key default gen_random_uuid(),
  org_id              uuid not null references public.organizations (id) on delete cascade,
  code                text,
  opened_by           uuid references public.employees (id) on delete set null,
  opened_at           timestamptz not null default now(),
  -- What was in the drawer before the first sale. Part of the count at close
  -- and not part of the takings, which is the arithmetic every arqueo gets
  -- wrong when the two are conflated.
  opening_float_cents bigint not null default 0 check (opening_float_cents >= 0),
  closed_at           timestamptz,
  closed_by           uuid references public.employees (id) on delete set null,
  -- Physically counted at close. Null while the session is open — a session
  -- with no count is not a session that counted zero.
  counted_cents       bigint check (counted_cents is null or counted_cents >= 0),
  -- Frozen at close from the orders attached to the session, so the arqueo
  -- stays a record of that night rather than a figure that drifts as old
  -- orders are edited.
  expected_cents      bigint check (expected_cents is null or expected_cents >= 0),
  status              text not null default 'Abierta'
                        check (status in ('Abierta', 'Cerrada')),
  notes               text not null default '',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (org_id, code)
);

create index cash_sessions_open_idx on public.cash_sessions (org_id, status, opened_at desc);

-- A closed session has been counted, and an open one cannot have been. Both
-- directions, because either half alone still allows the incoherent row.
alter table public.cash_sessions
  add constraint cash_sessions_close_consistent check (
    (status = 'Abierta' and closed_at is null and counted_cents is null and expected_cents is null)
    or
    (status = 'Cerrada' and closed_at is not null and counted_cents is not null and expected_cents is not null)
  );

create trigger cash_sessions_code before insert on public.cash_sessions
  for each row execute function app.set_code('cash_session', 'CAJ', '5');
create trigger cash_sessions_touch before update on public.cash_sessions
  for each row execute function app.touch_updated_at();

select app.apply_standard_rls('cash_sessions', 'restaurante:read', 'restaurante:write');

/**
 * At most one session open per organization.
 *
 * Two open tills mean every order has to guess which one it belongs to, and
 * the arqueo of both is wrong. A partial unique index says it once, at the
 * only layer that cannot be bypassed.
 */
create unique index cash_sessions_one_open
  on public.cash_sessions (org_id) where status = 'Abierta';

-- Orders belong to the session that was open when they were paid. A time
-- window would have been ambiguous at exactly the moment that matters — the
-- minutes around a shift change — so the link is explicit.
alter table public.restaurant_orders
  add column cash_session_id uuid references public.cash_sessions (id) on delete set null;

create index restaurant_orders_session_idx
  on public.restaurant_orders (cash_session_id) where cash_session_id is not null;

comment on column public.restaurant_orders.cash_session_id is
  'The till session this order was paid into. Set when the order is paid; what expected_cents is summed from.';

-- ─── Domicilios y para llevar ───────────────────────────────────────────────
-- The order table already knows what was ordered and what it cost. What it
-- cannot say is whether it left the building — and an order for delivery is
-- not «Servida» when it reaches the door, it is out of the restaurant's hands
-- and into a courier's.

alter table public.restaurant_orders
  add column service_kind text not null default 'Salón'
    check (service_kind in ('Salón', 'Domicilio', 'Para llevar'));

comment on column public.restaurant_orders.service_kind is
  'Where the order is served. «Salón» keeps the table-based behaviour; the other two are covered by restaurant_deliveries.';

create table public.restaurant_deliveries (
  id            uuid primary key default gen_random_uuid(),
  order_id      uuid not null references public.restaurant_orders (id) on delete cascade,
  courier_id    uuid references public.employees (id) on delete set null,
  address       text not null check (length(btrim(address)) between 1 and 240),
  phone         text not null default '',
  status        text not null default 'Pendiente'
                  check (status in ('Pendiente', 'En preparación', 'En camino', 'Entregado', 'Cancelado')),
  fee_cents     bigint not null default 0 check (fee_cents >= 0),
  dispatched_at timestamptz,
  delivered_at  timestamptz,
  notes         text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  -- One delivery per order: a single bill that went to two addresses is two
  -- orders, and allowing the row twice would double every delivery report.
  unique (order_id)
);

create index restaurant_deliveries_status_idx
  on public.restaurant_deliveries (status, created_at desc);

create trigger restaurant_deliveries_touch before update on public.restaurant_deliveries
  for each row execute function app.touch_updated_at();

select app.apply_child_rls('restaurant_deliveries', 'restaurant_orders', 'order_id',
                           'restaurante:read', 'restaurante:write');

-- The timestamps follow the status rather than being typed alongside it, so a
-- delivery cannot claim to have arrived before it left — or to be «Entregado»
-- with no arrival time at all, which is what makes a delivery-time report
-- quietly meaningless.
create or replace function app.stamp_delivery_status()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status in ('En camino', 'Entregado') and new.dispatched_at is null then
    new.dispatched_at := now();
  end if;
  if new.status = 'Entregado' and new.delivered_at is null then
    new.delivered_at := now();
  end if;
  -- Moving back out of a terminal state clears the stamp it implied: a
  -- delivery returned to «En camino» has not been delivered.
  if new.status <> 'Entregado' then
    new.delivered_at := null;
  end if;
  return new;
end;
$$;

revoke all on function app.stamp_delivery_status() from public, anon, authenticated;

create trigger restaurant_deliveries_stamp
  before insert or update on public.restaurant_deliveries
  for each row execute function app.stamp_delivery_status();
